version: '3'

services:
    mysqldb:
        image: mysql
        container_name: mysqlservice
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - ./database/config:/etc/mysql
            - ../mysqlbd/data:/var/lib/mysql
            - ./database/logs/:/var/log/mysql
        networks:
            - custom

networks:
    custom:
        external: true