version: '3.5'

networks:
    servicesnet:
        name: networkservices
        driver: bridge

services:
    mysqldb:
        image: mysql
        container_name: mysqlservice
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - ./database/config:/etc/mysql
            - ../databases/mysqlbd/data:/var/lib/mysql
            - ./database/logs/:/var/log/mysql
        networks:
            - servicesnet
